name: Devtation client CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create .env.production
        run: echo "${{ secrets.ENV_PRODUCTION }}" > .env.production

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devtation-client:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/devtation-client:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Pull the latest Docker image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/devtation-client:latest

            sudo docker stop devtation-client-container || true
            sudo docker rm devtation-client-container || true

            sudo docker run -d --name devtation-client-container -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/devtation-client:latest
